### ISSUE TITLE
TemHunter Startup Error

### ISSUE THREAD

**Issue by napros** [Mizogg/TeamHunter#13]
I have used this on my other computer and it works great, but when I reinstalled it onto another computer, this is the error I am now getting.

===================== RESTART: G:\TeamHunter\TeamHunter.py =====================
pygame 2.5.2 (SDL 2.28.3, Python 3.11.8)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "G:\TeamHunter\TeamHunter.py", line 444, in <module>
    window = MainWindow()
  File "G:\TeamHunter\TeamHunter.py", line 79, in __init__
    self.initUI()
  File "G:\TeamHunter\TeamHunter.py", line 201, in initUI
    ice_tool = ice_gui.GUIInstance()
  File "G:\TeamHunter\funct\ice_gui.py", line 88, in __init__
    self.initUI()
  File "G:\TeamHunter\funct\ice_gui.py", line 151, in initUI
    self.add_count_label = QLabel(self.count_addresses(), objectName="count_addlabel", alignment=Qt.AlignmentFlag.AlignLeft)
  File "G:\TeamHunter\funct\ice_gui.py", line 613, in count_addresses
    btc_bf_file = BTC_BF_FILE
NameError: name 'BTC_BF_FILE' is not defined

Could you please advise how to fix this so I can start using it again.  Thank you in advance (10/10 for this and your other scripts)

**Comment by ghost3666** [comment]
Useless you wont find anything with this tool, so why waste time, money and
power /electricity.....

**Comment by Mizogg** [comment]
Hi And thank you for you comments I am glad you like to use them.
I'm not sure why you and getting that error  BTC_BF_FILE not being defined. This error is occurring in the file ice_gui.py at line 613.

This kind of error typically happens when a variable that hasn't been declared or defined anywhere in the code. It has been declared in the config.py file.
BTC_BF_FILE = f"{INPUT_FOLDER}/{settings.value('Paths/BTC_BF_FILE', defaultValue='btc.bf', type=str)}"

If not a bloom file in that location it should use the txt file database either one of these should be stored inside the input folder.

Please make sure that you have these files, if you have transferred from your other computer maybe download again a fresh copy from GitHub and try again.

Thanks Mizogg
